import { createSlice } from "@reduxjs/toolkit";

export const TournamentSlice = createSlice({
  name: "TournamentSlice",
  initialState: {
    category: "history",
    data: [
      {
        id: 1,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 1, 14),
        endDate: new Date(2022, 10, 1, 19),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60, userimg: "user1" },
          { id: 2, name: "Hana Riva", power: 90, userimg: "user2" },
          { id: 3, name: "Alban Danell", power: 70, userimg: "user3" },
        ],
      },
      {
        id: 2,
        name: "Group Tournament",
        startDate: new Date(2022, 10, 1, 11),
        endDate: new Date(2022, 10, 1, 20),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
          { id: 5, name: "Alban Danell", power: 80 },
          { id: 6, name: "Bulat Peters", power: 50 },
          { id: 7, name: "Frank Ivers", power: 100 },
        ],
      },
      {
        id: 3,
        name: "Final Tournament",
        startDate: new Date(2022, 10, 1, 9),
        endDate: new Date(2022, 10, 1, 18),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
          { id: 5, name: "Alban Danell", power: 70 },
          { id: 6, name: "Bulat Peters", power: 50 },
        ],
      },
      {
        id: 4,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 11),
        endDate: new Date(2022, 10, 1, 15),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
        ],
      },
      {
        id: 5,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 12),
        endDate: new Date(2022, 10, 1, 21),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
          { id: 5, name: "Alban Danell", power: 80 },
          { id: 6, name: "Bulat Peters", power: 50 },
          { id: 7, name: "Frank Ivers", power: 100 },
          { id: 8, name: "Frank Ivers", power: 80 },
        ],
      },
      {
        id: 6,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 6),
        endDate: new Date(2022, 10, 1, 14),
        format: "Team",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 7,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 11),
        endDate: new Date(2022, 10, 1, 14),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 8,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 1, 9),
        endDate: new Date(2022, 10, 1, 11),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 9,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 1, 14),
        endDate: new Date(2022, 10, 1, 19),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 10,
        name: "Group Tournament",
        startDate: new Date(2022, 10, 1, 11),
        endDate: new Date(2022, 10, 1, 20),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 11,
        name: "Final Tournament",
        startDate: new Date(2022, 10, 1, 9),
        endDate: new Date(2022, 10, 1, 18),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 12,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 11),
        endDate: new Date(2022, 10, 1, 15),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 13,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 12),
        endDate: new Date(2022, 10, 1, 21),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 14,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 8),
        endDate: new Date(2022, 10, 1, 9),
        format: "Team",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 15,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 1, 5),
        endDate: new Date(2022, 10, 1, 10),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 16,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 1, 9),
        endDate: new Date(2022, 10, 1, 11),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
    ],
    sortedTournaments: [],
    tournament: {},
  },
  reducers: {
    switchCategory: (state, action) => {
      state.category = action.payload;
    },
    getTournamentFindById: (state, action) => {
      state.tournament = state.data.find(
        (tournament) => tournament.id == action.payload
      );
    },
    getTournamentFindBySearch: (state, action) => {
      state.sortedTournaments = action.payload;
    },
  },
});
export const TournamentReducer = TournamentSlice.reducer;
export const {
  switchCategory,
  searchTournament,
  getTournamentFindById,
  getTournamentFindBySearch,
} = TournamentSlice.actions;
