import { createSlice } from "@reduxjs/toolkit";

export const TournamentSlice = createSlice({
  name: "TournamentSlice",
  initialState: {
    data: [
      {
        id: 1,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 17, 14),
        endDate: new Date(2022, 10, 17, 19),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60, userimg: "user1" },
          { id: 2, name: "Hana Riva", power: 90, userimg: "user2" },
          { id: 3, name: "Alban Danell", power: 70, userimg: "user3" },
        ],
      },
      {
        id: 2,
        name: "Group Tournament",
        startDate: new Date(2022, 10, 17, 11),
        endDate: new Date(2022, 10, 17, 20),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
          { id: 5, name: "Alban Danell", power: 80 },
          { id: 6, name: "Bulat Peters", power: 50 },
          { id: 7, name: "Frank Ivers", power: 100 },
        ],
      },
      {
        id: 3,
        name: "Final Tournament",
        startDate: new Date(2022, 10, 17, 9),
        endDate: new Date(2022, 10, 17, 18),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
          { id: 5, name: "Alban Danell", power: 70 },
          { id: 6, name: "Bulat Peters", power: 50 },
        ],
      },
      {
        id: 4,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 11),
        endDate: new Date(2022, 10, 17, 15),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
        ],
      },
      {
        id: 5,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 12),
        endDate: new Date(2022, 10, 17, 21),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
          { id: 5, name: "Alban Danell", power: 80 },
          { id: 6, name: "Bulat Peters", power: 50 },
          { id: 7, name: "Frank Ivers", power: 100 },
          { id: 8, name: "Frank Ivers", power: 80 },
        ],
      },
      {
        id: 6,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 6),
        endDate: new Date(2022, 10, 17, 14),
        format: "Team",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 7,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 11),
        endDate: new Date(2022, 10, 17, 14),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 8,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 17, 9),
        endDate: new Date(2022, 10, 17, 11),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 9,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 17, 14),
        endDate: new Date(2022, 10, 17, 19),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 10,
        name: "Group Tournament",
        startDate: new Date(2022, 10, 17, 11),
        endDate: new Date(2022, 10, 17, 20),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 11,
        name: "Final Tournament",
        startDate: new Date(2022, 10, 17, 9),
        endDate: new Date(2022, 10, 17, 18),
        format: "Single",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 12,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 11),
        endDate: new Date(2022, 10, 17, 15),
        format: "Team",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 13,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 12),
        endDate: new Date(2022, 10, 17, 21),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 14,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 8),
        endDate: new Date(2022, 10, 17, 9),
        format: "Team",
        location: "MOS",
        court: "Hard",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 15,
        name: "Semi-Final Tournament",
        startDate: new Date(2022, 10, 17, 5),
        endDate: new Date(2022, 10, 17, 10),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
      {
        id: 16,
        name: "KIA Tournament",
        startDate: new Date(2022, 10, 17, 9),
        endDate: new Date(2022, 10, 17, 11),
        format: "Single",
        location: "MOS",
        court: "Clay",
        payment: 1000,
        participants: [
          { id: 1, name: "Bulat Peters", power: 60 },
          { id: 2, name: "Hana Riva", power: 90 },
          { id: 3, name: "Alban Danell", power: 70 },
          { id: 4, name: "Frank Ivers", power: 30 },
        ],
      },
    ],
    filterKeys: {
      text: "",
      category: "history",
    },
    tournament: {},
  },
  reducers: {
    getTournamentFindById: (state, action) => {
      state.tournament = state.data.find(
        (tournament) => tournament.id == action.payload
      );
    },
    setFilterKeys: (state, action) => {
      const { text, category } = action.payload;
      text != undefined ? state.filterKeys.text = text : state.filterKeys.category = category
    },
  },
});
export const TournamentReducer = TournamentSlice.reducer;
export const {  searchTournament, getTournamentFindById ,setFilterKeys} =
  TournamentSlice.actions;
